### ISSUE TITLE
BioGrid

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#10]
1. Header not appearing
2.   BioGRID doesn't curate japonicus

<img width="1216" alt="Screenshot 2021-05-14 at 00 51 33" src="https://user-images.githubusercontent.com/7359272/118247685-5ee61680-b49b-11eb-8690-c16369648519.png">

**Comment by kimrutherford** [comment]
> Header not appearing

I think I fixed that earlier today.  Could you try reloading?

**Comment by ValWood** [comment]
Ah right. My screenshot was from last night. You are ahead of me.

**Comment by kimrutherford** [comment]
> BioGRID doesn't curate japonicus

I'll remove BioGRID for japonicus.

**Comment by kimrutherford** [comment]
> BioGRID doesn't curate japonicus

I've changed it to say:

```
Source: Interactions curated by JaponicusDB
```

but maybe we should just hide that text for japonicus?

**Comment by ValWood** [comment]
Makes sense....

**Comment by kimrutherford** [comment]
> maybe we should just hide that text for japonicus?

I've done that now.
