### ISSUE TITLE
Add UniProt protein feature data for japonicus

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-config#102]
Using the UniProt API we can download data for displaying in the protein feature viewer.  Like we did for PomBase: pombase/pombase-chado#52

I've downloaded a japonicus data file and added to SVN for when we have time to configure this:
`pombe-embl/external_data/uniprot_data_from_api_japonicus.tsv`

There is less information for japonicus than for pombe but more than I expected.

**Comment by ValWood** [comment]
excellent!

**Comment by kimrutherford** [comment]
That's done now.  The list of imported modification annotations is here:
https://www.japonicusdb.org/reference/PMID:36408920

We also get some features in the protein feature viewer for signal peptides, [transit peptides](https://www.japonicusdb.org/gene_protein_features/SJAG_02353), chains, binding site and active sites:

--------------------------------------

https://www.japonicusdb.org/gene_protein_features/SJAG_02827
![image](https://github.com/user-attachments/assets/96b0cf01-5fa8-4cd1-b478-6a692d554c3f)

--------------------------------------

https://www.japonicusdb.org/gene_protein_features/SJAG_03009
![image](https://github.com/user-attachments/assets/e102e26a-f638-4c65-b52b-99689b0fa2af)
