### ISSUE TITLE
Add disease associations and the Mondo disease ontology

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-config#104]
Now we've streamlined the way we include disease associations it should be straight forward to copy and paste the configuration and data loading steps from PomBase to JaponicusDB.

**Comment by kimrutherford** [comment]
I don't know how useful disease associations will be but it seemed a shame not to provide the data since it was available.

So there is now a japonicus disease slim overview:
   https://www.japonicusdb.org/browse-curation/disease-slim

Disease pages:
  https://www.japonicusdb.org/term/MONDO:0005570

Query by disease:

![image](https://github.com/user-attachments/assets/aec409a6-05cb-4832-9b9e-d5b1d3b06db8)

And the there is a disease section on gene pages:

![image](https://github.com/user-attachments/assets/af72ce8f-3cc5-4796-9f4a-e0950f43cae6)

@snezhkaoliferenko

**Comment by snezhkaoliferenko** [comment]
Thank you!!

________________________________
