### ISSUE TITLE
considerations  for inferring GO annotations for japonicus

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#11]
This is what we discussed. We can mull over to see if we  overlooked anything:

Take the PomBase GAF EXP,IMP,IDA,IGI,ISM,ISO data
(We can think if we want to use IPI in some contexts later, possibly for terms other than 'protein binding' because these will require that we also import the 'with' field and convert it.

For all 1:1 orthologs
Go through the GO GAF
- Replace the  PomBase:XXXXX with the  japonicus  ID
- Replace the evidence code with IEA
- Replace the ref with GO_REF:?????
- Strip out the with/from field, column 16 and column 17 
- Add with=PomBase:XXXXX to the 'with' field

When these are imported, give them the lowest precedence.
Also do not import for any gene/aspect with a NOT annotation  (we need to make sure the japonicus community know if they use a NOT they need to make all annotations they intend to keep manually.

Outstanding questions.
- What to do about HDA (orfeome localization data mainly) , note this still has false positives for fission yeast, we are still cleaning these up. Taking everything into account they will probably be useful.

**Comment by kimrutherford** [comment]
Thanks for that detail Val.

It all sounds good except could you explain this bit?:

> When these are imported, give them the lowest precedence.

**Comment by ValWood** [comment]
> When these are imported, give them the lowest precedence.

 actually this won't be possible.   ignore. All the IEA will need to have the same precedence.
Later we will try to think of a way to get a better evidence code, but for now everything will be IEA except our Canto stuff (I imagine?).

**Comment by kimrutherford** [comment]
> actually this won't be possible. ignore. All the IEA will need to have the same precedence.

OK, thanks.

> but for now everything will be IEA except our Canto stuff (I imagine?).

Yep, almost everything.  Except for 10 ISS annotation from GOA.

**Comment by kimrutherford** [comment]
After we implement this, will we stop loading GOA?  I'm worried about duplicate annotation.

> For all 1:1 orthologs

Is there anything useful we can do via 1-many and many-1 orthologs?

> Also do not import for any gene/aspect with a NOT annotation

I probably won't do that on my first attempt as it's a bit trickier.

**Comment by ValWood** [comment]
> After we implement this, will we stop loading GOA? I'm worried about duplicate annotation.

I think it is OK to load, because any duplicate annotation will get filtered? If it is possible to load in an order that would give  our IEA precedence it would be good, but not totally necessary. We are only concerned about getting GO annotations, whatever the source. We need both though (see below).

> Is there anything useful we can do via 1-many and many-1 orthologs?

I don't currently have a good feeling about how many orthologs are not 1:1. Once we know this we can devise a strategy- I think it isn't too many. They are likely to be 2 types:
The ones I think of as 'evolving duplicates', things that are duplicated and diverge (neofunctionalise), signalling molecule, transcription factors and transmembrane transporters (i.e proteins which interact with, or get information from the external environment). GOA will be useful for getting the annotations for these. In fact, for some of this is a class PomBase often totally depend on GOA because I haven't manually annotated them all yet.
e.g. 
https://www.pombase.org/gene/SPCC1682.11c
https://www.pombase.org/gene/SPBC1683.08
https://www.pombase.org/gene/SPAC9E9.12c
- these will get annotated by InterPro from GOA

The other class is the highly conserved duplicates, like histones and ribosomal proteins. These are core conserved genes but are duplicated (usually) to increase copy number (expression), or possibly for robustness. Here the duplicates are highly similar (often 100% identical). These should also get annotations from GOA, but I plan to manually check these (especially the histones), and name them sensibly to avoid future confusion.


Because most (I hope) are going to be 1:1 I think we will get good coverage with this strategy. Once we know where the gaps are, we can look at also transferring from  1:many many:1 many:many.
It might be fairly safe to do this also. However, there will be tricky differences, for example, I think mid2 might be a pombe specific paralog (I tried to check this in the  Ensembl Compara gene tree, but  it is giving an error).

Do you know how many are 1:1?
The interesting ones will be japonicus specific (if these are conserved they might get annotated by GOA). If we can get a list of these  we can add some controlled curation for . Some of  taxonomic conservation. Most of our taxonomic conservation annotation will map straight over. 
I'll make a ticket for this soon.

**Comment by kimrutherford** [comment]
There are 4085 1-1 orthologs from Compara.

52 japonicus genes have multiple orthologs in pombe.  (1-many?)

35 pombe genes have multiple orthologs in japonicus.  (many-1)

And there are a bunch of many-many orthologs.

If you'd like to explore, here are the pombe genes that have japonicus orthologs:
[pombe_genes_with_japonicus_ortholog.txt](https://github.com/japonicusdb/japonicus-config/files/6492640/pombe_genes_with_japonicus_ortholog.txt)

You can paste them into ID mapper: http://japonicusdb.kmr.nz/identifier-mapper

**Comment by ValWood** [comment]
cool.  It seems like there will not be too many to resolve for GO.  we might  be able to automate further.

**Comment by ValWood** [comment]
Well that is pretty much as I expected:
https://www.pombase.org/results/from/id/61f5c358-f40b-4541-a2a1-0ec19a615b76

(except not all the histones are here, so some histone must incorrectly classed as 1:1 by compara).

One small improvement, we clearlly hav en't loaded the mitochondrial genome. I'm surre this is avaiable (even from an earlier source than the Rhind paper. I will have a poke around for that).

The only other surprise is that there are quite a lot of mitochondrial proteins (nuclear encoded), that I would expect to be 1:1. A lot of these have very low levels of conservation, so they are probably below the resolution for Compara.

**Comment by ValWood** [comment]
yes, this is largely a list of distant orthologs. I might need to link these up manually if they aren't covered by any ortholog predictor. I will  check to see if panther is bettter here (It should be).

https://www.pombase.org/results/from/id/2603cf2b-f91b-4d3b-807b-9a0d0a02e13c

**Comment by ValWood** [comment]
I think wecan use this  GOREF to describe our annotation

Automatic transfer of experimentally verified manual GO annotation data to orthologs using Ensembl.
id: GO_REF:0000107
year: 2016
authors: GOA curators
GO terms from a source species are projected onto one or more target species based on gene orthology obtained from Ensembl. One to one, one to many and many to many orthologies are used but annotations are only projected between orthologs that have at least a 40% peptide identity to each other. Only GO annotations with evidence codes ECO:0000314 (IDA), ECO:0000270 (IEP), ECO:0000316 (IGI), ECO:0000315 (IMP), and ECO:0000353 (IPI), or their descendants, are projected; annotations with a 'NOT' qualifier are not projected, and neither are annotations to GO:0005515 (protein binding). Annotations that are projected using this technique receive the evidence code ECO:0000265 (sequence orthology evidence used in automatic assertion), which maps up to the GO Inferred from Electronic Annotation (IEA) evidence code. The model organism database identifier of the annotation source will be indicated in the 'With' column of the GOA association file.

However, to be compliant,  when we transfer annotations  with. an ISO/ISS evidence code
we should use the object  that is already in the with field rather than the pombe ortholog ID.

i.e. if pombe gene x has gene A in the "with" field  is ortholog  of japonicus gene y. japonicus gene y is also ortholog of gene A (since we are only transferring for 1:1 at the moment).

- [ ] also remember not to transfer anything with a NOT qualifier  in fission yeast, in addition to transferring anything to a gene in s.j with a NOT qualifier

**Comment by ValWood** [comment]
FYI:
https://github.com/geneontology/helpdesk/issues/313

**Comment by ValWood** [comment]
Although we won't be using the 40% cut off (why?? an ortholog is an ortholog), so maybe we do need a new GO ref after all.

**Comment by kimrutherford** [comment]
I've mostly done this now.

What should the date be for the transferred annotations?  The original date in the GAF file or the date the mapping is done?

**Comment by kimrutherford** [comment]
Do we need to process the Qualifier column at all, or can it be passed through?

**Comment by ValWood** [comment]
the date the mapping is done.

this will be cool, let me know when to look!

**Comment by ValWood** [comment]
contributes_to and colocalizes_with can be passed through (I think we almost eradicated colocalized with?)

NOTs  can probably be ignored. At the moment it would probably not be so bad to transfer them, but  they aren't absolutely necessary, and going forwards we are more likely to use them to indicate differences from japonicus so it will be important not to transfer them.

**Comment by kimrutherford** [comment]
This is live now but it's not quite right as all the "IEA with" links don't go to PomBase.  The data seems OK otherwise.

**Comment by kimrutherford** [comment]
> it's not quite right as all the "IEA with" links don't go to PomBase

That's fixed now.

It's looking good I think.  We've gone from 2765 genes with a function annotation to 3299, and from 2594 to 3436 with a BP annotation.

**Comment by ValWood** [comment]
Yes that is much improved!

These are the ones without a GO process:
http://japonicusdb.kmr.nz/gene_subset/non_slim_without_biological_process_annotation

Some of them should have a  BP process, since they have a gene name/product,and they have MF and CC transferred.

The first one I looked at was rpn3
https://www.pombase.org/gene/SPBC119.01
and our annotation here are IC so I wonder if some evidence codes are being ignored. We can include ALL evidence codes for this purpose.

**Comment by kimrutherford** [comment]
> our annotation here are IC so I wonder if some evidence codes are being ignored. We can include ALL evidence codes for this purpose.

Yep, we're ignoring most of the evidence codes because you said:

> Take the PomBase GAF EXP,IMP,IDA,IGI,ISM,ISO data

So those are the only annotations that are transferred at the moment.

Should we change that?

**Comment by ValWood** [comment]
Yes please. I didn't realise how many of ours has IC/NAS/TAS only.
Quite a few of the unstudied genes from big complexes  (splicosome/proteasome etc) I annotated the process with IC from the complex. I think for PoMBase we currently give IC higher priority so many genes will have  IC only.  Later we will probably prioritise IBA but I am still correcting lots of PAINT annotations:
https://github.com/geneontology/go-annotation/issues/created_by/ValWood

I don't know why I said only those evidence codes. If I thought about it properly it would be obvious we need them all.....(I am happy with the quality of the IC/NAS/TAS)

**Comment by kimrutherford** [comment]
OK.

This is the file we're loading: https://curation.pombase.org/dumps/builds/pombase-build-2021-05-26/pombase-build-2021-05-26.gaf.gz

So just to check: we want everything from that file?

Do IGI annotation need special handling?  Earlier you said:

> We can think if we want to use IPI in some contexts later, possibly for terms other than 'protein binding' because these will require that we also import the 'with' field and convert it.

**Comment by ValWood** [comment]
I think we want all evidence codes. But we should omit the  MF term "protein binding" because at present we are ignoring the "with field" and without that "protein binding" doesn't make any sense.

All the IGIs will be OK. They  work as stand-alone annotations without the "with'field.

**Comment by kimrutherford** [comment]
> But we should omit the MF term "protein binding"

Does that mean "protein binding" and descendants?  If so that will take a bit of work because currently the script has no knowledge of the ontology structure.  It's just parsing the GAF file and orthologs table file, then writing a GAF file.  To get the descendants it will need to do Chado querying and filter based on the results.  That'll need a bit of reorganising of the script so I might not try it today.

**Comment by kimrutherford** [comment]
> I think we want all evidence codes.

I made that change but then realised we're transferring ND annotations and changing the evidence to "IEA".  Whoops.  I'll fix that.

**Comment by kimrutherford** [comment]
> realised we're transferring ND annotations and changing the evidence to "IEA". Whoops. I'll fix that.

That's done now.  All the pombe annotation is now included and ND annotations from the GAF are ignored.

We're not excluding protein binding annotations yet.

Now I've thought about it I'm wondering why we are using IEA rather than ISO for the transferred annotations?

**Comment by ValWood** [comment]
This is looking good.


 Yes we discussed making them ISE but possible;y upgrading to ISO oncer we are happy with the quality. 3839 genes now have a  GO process, 1049 without (most either unknown or multi gene families).

I will try to figure a  quick way to get products lines and possible GO annotation on these.

**Comment by ValWood** [comment]
If we include the Rhind orthologs first. I'm sure somebody must have a simple table of these.

After that, I can  use Interpro to pull out the multigene families and annotate those.

**Comment by kimrutherford** [comment]
> But we should omit the MF term "protein binding"

I've changed the implementation and config so that we are now omitting protein binding and descendants.  Also the Rhind orthologs are used for annotation transfer.

I'm doing a test load.

**Comment by ValWood** [comment]
Is the test load up yet? I will check it.

**Comment by kimrutherford** [comment]
Sorry, it's not ready yet.  I ran into some unrelated problems that needed fixing.  I haven't been able to complete a test load on my desktop but I think I've fixed all the problems now.

(I upgraded my desktop over the weekend and one of the older Perl modules used all over the loading code is now unsupported.  This is likely to happen next time the oliver1 is updated so I went through changed the code to avoid using the module.  It took a while to get things working again)

**Comment by ValWood** [comment]
ok! i have a lot on my to do list today anyways...

**Comment by kimrutherford** [comment]
It looks like it's all working now.  I've loaded the new JaponicusDB on a "dev" site: http://dev.japonicusdb.kmr.nz/

If it's OK, I'll update the main JaponicusDB site.

> This is likely to happen next time the oliver1 is updated so I went through changed the code to avoid using the module

If I've made any typos, these changes might cause problems for the PomBase nightly load tonight.  I'll have a good look in the morning before releasing the update.

**Comment by kimrutherford** [comment]
> I've loaded the new JaponicusDB on a "dev" site: http://dev.japonicusdb.kmr.nz/
> If it's OK, I'll update the main JaponicusDB site.

I've updated the main site because I wanted to fix the chromosome details.

**Comment by kimrutherford** [comment]
> I've changed the implementation and config so that we are now omitting protein binding and descendants. Also the Rhind orthologs are used for annotation transfer.

We went from 4477 annotated genes to 4545 after this change which is a nice confirmation.  And from 29037 to 28556 GO annotations in the exported GAF file (presumably because of filtering protein binding annotations).

Let me know if you're like the GAF files from before or after.  We're generating them from each load but they aren't on the web yet.

Can this be closed now?

**Comment by ValWood** [comment]
Yes. I am still working on products and for the ones which have no orthologs,  or are 1:1 1:many many:many.

We will  likely be able to transfer the GO annotations on these, but I will check if there is anything that should not be inferred when I do the products.

I will open new tickets for new things.
