### ISSUE TITLE
3 spotlights for japonicus

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#13]
{
      "title": "Gu et al., 2015",
      "title_link": null,
      "panel_type": "spotlight",
      "head_image": ["spotlight/Mid1-Gu-Oliferenko-25866389.png"],
      "content": "Rewiring of cellular division site selection in evolution of fission yeasts..\nOriginally published in <a href='Curr Biol'>https://doi.org/10.1016/j.cub.2015.02.056</a>.",
      "reference_id": "PMID:25866389",
      "link_label": "Publication record in Japonicus DB ...",
      "date_added": "2021-05-12",
      "show_on_front_page": true
      },
     "title": "Gómez-Gil et al., 2020",
      "title_link": null,
      "panel_type": "spotlight",
      "head_image": ["spotlight/Sty1-32915139-Cansando.png"],
      "content": "Stress-activated MAPK signalling controls fission yeast actomyosin ring integrity by modulating formin For3 levels.\nOriginally published in <a href='https://elifesciences.org/articles/57951'>eLife</a>.",
      "reference_id": "PMID:32915139",
      "link_label": "Publication record in Japonicus DB ...",
      "date_added": "2021-05-13",
      "show_on_front_page": true
      },
      {
      "title": "An et al., 2021",
      "title_link": null,
      "panel_type": "spotlight",
      "head_image": ["spotlight/Mis16-An_Cho-26343758.png"],
      "content": "Mis16 Independently Recognizes Histone H4 and the CENP-ACnp1-Specific Chaperone Scm3sp.\nOriginally published in <a href='https://doi.org/10.10/j.jmb.2015.08.022'>J Mol Biol</a>.",
      "reference_id": "PMID:26343758",
      "link_label": "Publication record in Japonicus DB ...",
      "date_added": "X2021-05-13",
      "show_on_front_page": true
      },

**Comment by ValWood** [comment]
![Uploading Mid1-Gu-Oliferenko-25866389.png…]()
<img width="309" alt="Mis16-An_Cho-26343758" src="https://user-images.githubusercontent.com/7359272/118404513-26953280-b66b-11eb-89e2-807a342c7c26.png">
![Uploading Sty1-32915139-Cansando.png…]()

**Comment by kimrutherford** [comment]
Thanks.

I'm going hold off on these a little while.  I'm going to have a think about putting the japonicus spotlights (and other images) it their own directory.

**Comment by kimrutherford** [comment]
I've added these three now: http://japonicusdb.kmr.nz/archive/spotlight

I added the date to the image file names.

Let me know if you spot any problems.

The procedure for new Spotlights is the same as for PomBase except that the configuration file is `japonicus_site_config.json` in the `japonicus-config` directory.

**Comment by ValWood** [comment]
Nice!

@snezhkaoliferenko  if you would like to add more  we just need a suitable sized image to create a spotlight.
v

**Comment by snezhkaoliferenko** [comment]
@ValWood @kimrutherford the images are swapped ;)
our paper (Gu et al) should have the image with Rlc1 and actin
Gomez-Gil et al, the one with sty1del
and the crystal structure goes to An et al

**Comment by kimrutherford** [comment]
> the images are swapped ;)

Thanks for checking.  That's fixed now.

**Comment by snezhkaoliferenko** [comment]
@kimrutherford 
sorry - there are still two images that need to be swapped - the crystal structure belongs to An et al, 2021 and the image with Rlc1 and LifeAct to Gu et al, 2015
thanks!

**Comment by kimrutherford** [comment]
Hi Snezhka.

Could you have a look and see if it's right this time?:
  http://japonicusdb.kmr.nz/archive/spotlight

You might need to reload to see the change.

**Comment by snezhkaoliferenko** [comment]
@kimrutherford yes! thank you

**Comment by kimrutherford** [comment]
I'm glad it was right this time. :-)
