### ISSUE TITLE
Annotation number

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#15]
Last updated 2021-05-16: 15280 annotations from 4 curated publications

Number of annotations looks a bit high ;)

**Comment by kimrutherford** [comment]
It's the same code as for PomBase.  There are 15280 annotations and there are 4 curated publications.  Should we change the wording or change the calculation?

PomBase says "282722 annotations from 4066 curated publications" but not all of the 282722 are from curated publications.  That number includes high throughput and all of the GOA annotations.

**Comment by ValWood** [comment]
Of course. I forgot about the inferred GO annotations.

Maybe we should change
 282726 annotations from 4067 curated publications
to
 282726 annotations AND 4067 curated publications

@mah11  ideas?

**Comment by mah11** [comment]
This isn't something I think about often, or, tbh, care about much. But maybe a bit of punctuation instead of a word? (E.g. 4067 curated publications &mdash; 282726 annotations)

tangent: I find it jarring that the 4067 is bright red.

**Comment by ValWood** [comment]
> tangent: I find it jarring that the 4067 is bright red.

that was temporary for a milestone. It can be black again now.

**Comment by kimrutherford** [comment]
> It can be black again now.

It will be black again for PomBase tomorrow morning.

**Comment by kimrutherford** [comment]
Here are a few options for reformatting of the stats section.  Any preferences?:

1.
![stats-1](https://user-images.githubusercontent.com/90474/121614876-c780dd00-cab3-11eb-872a-afcd43e1a2ea.png)

2.
![stats-2](https://user-images.githubusercontent.com/90474/121614881-ca7bcd80-cab3-11eb-94d1-c591d86e412b.png)

3.
![stats-3](https://user-images.githubusercontent.com/90474/121614884-cd76be00-cab3-11eb-9cd5-1efa609c018f.png)

4.
![stats-4](https://user-images.githubusercontent.com/90474/121615249-876e2a00-cab4-11eb-8d50-ef451edec9e5.png)

**Comment by ValWood** [comment]
I prefer 2.
It makes the numbers more prominent but does not take as much space as 4.
I had been thinking of suggesting a line split here for PomBase.

**Comment by mah11** [comment]
I rank 'em (4 tied with 3) > 2 > 1

**Comment by kimrutherford** [comment]
Thanks.  I've made the code change.

JaponicusDB will be updated with the change in a hour or so.  I haven't done a full load in a few days and this prompted me.

The change will be in PomBase on Saturday morning.
