### ISSUE TITLE
Publication link on front page

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#16]
http://japonicusdb.kmr.nz/reference/null

can link the front page publication link to one of Snezhana's papers now.

**Comment by kimrutherford** [comment]
I've changed it to this for the next release:
  http://japonicusdb.kmr.nz/reference/PMID:25866389

It's got a few different data types.

**Comment by ValWood** [comment]
Mabe fix. the example gene to SJAG_01143 too?

**Comment by kimrutherford** [comment]
> Mabe fix. the example gene to SJAG_01143 too?

I've committed a change to the config, which will appear next time I update.
