### ISSUE TITLE
S. japonicus mitochondrial genome

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#18]
https://www.ncbi.nlm.nih.gov/nuccore/AF547983

**Comment by kimrutherford** [comment]
> https://www.ncbi.nlm.nih.gov/nuccore/AF547983

There are no /locus_tag qualifiers in that entry.  We'll need to add them somehow.

**Comment by ValWood** [comment]
I suggest we just 'mint' them

SJAGMIT_01
SJMIT_01

(I don't know what the 'AG' is for in the genome IDs do you?)

**Comment by kimrutherford** [comment]
> I don't know what the 'AG' is for in the genome IDs do you?

I can't work it out.  Maybe an internal Broad ID scheme?  The octosporus gene IDs start with "SOCG"

**Comment by kimrutherford** [comment]
Do we need to add "MIT" in the newly minted IDs?  It seems a bit inconsistent.

**Comment by kimrutherford** [comment]
(Sorry for all the comments)

So:
  - "SJAG": S.JAponicus Gene
  - "SOCG": S.OCtosporus Gene
  - "SPOG": S. (no idea) Gene

:-)

**Comment by ValWood** [comment]
Right.

Yes, I think we should include the "MIT" in the label. It is inconsistent, but it is *really* useful. It has alerted me lots of times to issues when I'm doing genome wide queries etc.

PomBase and SGD both have totally different IDs for mitochondrial genes and I have been thankful for  this numerous times.

**Comment by ValWood** [comment]
Great detective work !

**Comment by kimrutherford** [comment]
So:
  - (A) "SJAMITG_..."
  - (B) "SJAGMIT_..."
  - (C) "SJAG_MIT_..."
  - (D) something else

I have a slight preference for (A)

**Comment by ValWood** [comment]
OK (A)

**Comment by kimrutherford** [comment]
Great.  Should I go ahead and add IDs to the AF547983 entry and include it with the other contigs?

**Comment by ValWood** [comment]
yes please. that will match up some more orthologs...

**Comment by kimrutherford** [comment]
There are 37 genes, so we get IDs: "SJAMITG_01" to "SJAMITG_37".  Are they too ugly?  I'm having second thoughts?

I'm doing a test load now.

**Comment by kimrutherford** [comment]
The mito contig is now loaded.  I added some potential orthologs by doing a BLAST and taking matches with a tiny E value.  I mostly did that so that some gene names and products would show up.  The orthologs are here if you're like to edit: https://github.com/japonicusdb/japonicus-curation/blob/main/pombe_orthologs.tsv

Here's an example gene:
http://japonicusdb.kmr.nz/gene/SJAMITG_13

JBrowse: http://japonicusdb.kmr.nz/jbrowse/?loc=mitochondrial%3A21806..41806&tracks=Forward%20strand%20features%2CReverse%20strand%20features&highlight=

**Comment by ValWood** [comment]
> There are 37 genes, so we get IDs: "SJAMITG_01" to "SJAMITG_37". Are they too ugly? I'm having second thoughts?

When I look at these labels I don't immediately think 'oh that's mitochondrial genome'

I think that
SJAG_MIT01
SJAG_MIT02
etc would be better.

**Comment by kimrutherford** [comment]
> I think that SJAG_MIT01

OK.  I'll change that tomorrow.

**Comment by ValWood** [comment]
> The mito contig is now loaded. I added some potential orthologs by doing a BLAST and taking matches with a tiny E value. I mostly did that so that some gene names and products would show up. The orthologs are here if you're like to edit: https://github.com/japonicusdb/japonicus-curation/blob/main/pombe_orthologs.tsv

just for the mitochondrial ones right?
I think the none conserved are dubious, from the days when all orfs were flagged.

**Comment by kimrutherford** [comment]
> just for the mitochondrial ones right?

Yep.

**Comment by ValWood** [comment]
OK thanks,
note to self
these are the ones to be linked up:

SPMIT.02 | cox1-I1b | mitochondrial DNA binding endonuclease Cox1-I1b (intron-encoded)
SPMIT.03 | cox1-I2b | mitochondrial DNA binding endonuclease (intron encoded)
SPMIT.08 | var1 | mitochondrial ribosomal protein subunit S3
SPMIT.06 | &nbsp; | mitochondrial DNA binding endonuclease (intron encoded)

with

SJAMITG_05 | &nbsp; | orf333
SJAMITG_06 | &nbsp; | orf307
SJAMITG_07 | &nbsp; | orf281

I'll take a look at these.

**Comment by kimrutherford** [comment]
> I think that
> SJAG_MIT01
> SJAG_MIT02
> etc would be better.

That's done now.

**Comment by ValWood** [comment]
SJAG_MIT05 -> cox1-I1b. (Pombe cox1-I1b)
SJAG_MIT06 -> cox1-I2a. (Pombe cox1-I2b, i.e many->1
SJAG_MIT07 -> cox1-I2b. (Pombe cox1-I2b).i.e many->1
(Slightly different from the compare orthologs)

Also I don't think thee mitochondrial translation table is being used. If it is I might need to tweak the gene structures.

 I will put the task of looking for
SPMIT.08 | var1 | mitochondrial ribosomal protein subunit S3
SPMIT.06 |   | mitochondrial DNA binding endonuclease (intron encoded)
on the curation tracker for a rainy day.

**Comment by kimrutherford** [comment]
> Also I don't think thee mitochondrial translation table is being used. If it is I might need to tweak the gene structures.

Sorry, you're right.  It was using the standard translation table.  These two genes had extra stop codons:  SJAG_MIT05 SJAG_MIT07

The translations of the other mito. genes are OK.

I've fixed the code and re-released so what you see now should be correct.

**Comment by kimrutherford** [comment]
I think this is done now.
