### ISSUE TITLE
footer stuff

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#22]
remember we need to change the footer and the logos at the bottom.
I'm not sure what should actually be there!

JaponicusDB is funded by the Wellcome Trust, run by a consortium comprising the University of Cambridge, University College London, and hosted by the Babraham Institute. JaponicusDB is an ELIXIR-UK Node Service

**Comment by kimrutherford** [comment]
> I'm not sure what should actually be there!

Me neither.  But for now I've removed mention of Babraham and removed "JaponicusDB is an ELIXIR-UK Node Service".

And a question for Snezhka: should we mention King's College or the Crick and/or have their logos?

**Comment by ValWood** [comment]
JaponicusDB was established with support from the Wellcome Trust. 
Say something about community maintenance.

**Comment by mah11** [comment]
new draft text:

JaponicusDB was established with support from the [Wellcome Trust](https://wellcome.org/), is maintained by a collaboration among the [University of Cambridge](https://www.cam.ac.uk/), the [Francis Crick Institute](https://www.crick.ac.uk/), and [King's College London](https://www.kcl.ac.uk/), and is hosted by the [Babraham Institute](https://www.babraham.ac.uk/).

Logos: Wellcome, Cambridge U., Crick, KCL

Decide whether to add Cambridge Sys Biol & Biochem dept. (use neither or both, but not just one).

**Comment by mah11** [comment]
obvs remove "and is hosted by Babraham" if they don't end up hosting it (or if they are but we don't want to draw attention to it)

**Comment by ValWood** [comment]
Should we add a comment along the lines "All curation will be performed by the _S. japonicus_ community volunteers coordinated by Snezhana Oliferenko"

Or similar. I want it to be really clear that we are not maintaining it with any of our WT funds. Especially as we are displaying the WT logo, and our grant officer is not the person who authorised  @snezhkaoliferenko  fund repurposing.

**Comment by mah11** [comment]
That really doesn't sound like page footer stuff. It would find a good home on the "About JaponicusDB" page that will come into existence when Kim and I are done with #3.

**Comment by ValWood** [comment]
In that case can we edit   to:

JaponicusDB was established with support from the Wellcome Trust, using code developed at University of Cambridge, is maintained by a collaboration lead from the Francis Crick Institute, and King's College London, and is hosted by the Babraham Institute.

**Comment by mah11** [comment]
Not in the sodding footer - it's not the place for that much detail about code.

Draft 2:
- JaponicusDB was established with support from the [Wellcome Trust](https://wellcome.org/), and is maintained by a collaboration led by the [Francis Crick Institute](https://www.crick.ac.uk/) and [King's College London](https://www.kcl.ac.uk/), with contributions from [PomBase](https://www.pombase.org/)  ([University of Cambridge](https://www.cam.ac.uk)). JaponicusDB is hosted by the [Babraham Institute](https://www.babraham.ac.uk/).


Draft 3:
- JaponicusDB was established with support from the [Wellcome Trust](https://wellcome.org/). The *S. japonicus* community maintains JaponicusDB, led by the [Francis Crick Institute](https://www.crick.ac.uk/) and [King's College London](https://www.kcl.ac.uk/), with contributions from [PomBase](https://www.pombase.org/) ([University of Cambridge](https://www.cam.ac.uk)). JaponicusDB is hosted by the [Babraham Institute](https://www.babraham.ac.uk/).


(in any case, include or exclude the Babraham sentence depending on what we decide)

**Comment by ValWood** [comment]
Either, just need to be clear publicly  that we are not curating, especially in such close proximity to the WT logo.

**Comment by snezhkaoliferenko** [comment]
if WT is a concern since they fund you, we could simply cite my grant from which it was funded? as we do in acknowledgements to papers? or TMI?
________________________________

**Comment by ValWood** [comment]
I think it is fine with either of the revised texts.

We don't want to rattle any cages.

**Comment by mah11** [comment]
We could put some grant details on the "About" page.

**Comment by kimrutherford** [comment]
I've committed "Draft 3", which should be visible in the morning.

I'm working on the logos.  It's one of the remaining things that is hard-coded which I'm fixing now.

If the text needs tweaking, it's in the japonicus-config repo here: https://github.com/japonicusdb/japonicus-config/blob/main/japonicus_site_config.json#L14

**Comment by kimrutherford** [comment]
> Remove elixir and UCL logos
> Add Crick and Kings logos

So just to confirm, we want these logos: WT, Cambridge, CSBC, Crick, Kings.

Does the order matter?

**Comment by ValWood** [comment]
@snezhkaoliferenko  can decide.
I don't think it really matters.

**Comment by kimrutherford** [comment]
The updated text and logos are on japonicusdb.org now.

The logos can be added, removed and reordered using the config file:
  https://github.com/japonicusdb/japonicus-config/blob/main/japonicus_site_config.json#L16
