### ISSUE TITLE
product descriptions

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#23]
These are the products with Interpro domains. Most seem to be multi gene families so the orthology calls will need to be done later.

http://japonicusdb.kmr.nz/results/from/id/fa23aee8-fa09-4c7f-a4dd-5710ce3bf8ec

For there as a first pass could  you provide the names from the contigs. I can edit these but it would b e a good starting point because for a lot I would not need to go to each gene page, I can just standardize the family label.

**Comment by ValWood** [comment]
these are the ones without Interpro domains.
These will either be rapidly diverging or japonicus specific.
If you could also provide the existing names for these to edit that would be useful.

Once we have done this I can check the  broadly conserved 1:1s and see if any are missing from the ortholog list  (the rapidly diverging ones).

**Comment by kimrutherford** [comment]
> For there as a first pass could you provide the names from the contigs.

I don't understand this bit.  Those genes don't have names.

**Comment by ValWood** [comment]
For there as a first pass could you provide the names from the contigs.

sorry I meant the 'product lines'

**Comment by kimrutherford** [comment]
Is this what you need?:  [interpro-genes-products.tsv.txt](https://github.com/japonicusdb/japonicus-config/files/6521345/interpro-genes-products.tsv.txt)

**Comment by ValWood** [comment]
perfect. As I thought it is distsant orthologs and multi gene families.

I will pull out the distant ortholog ones, hopefully today and we can add those.

**Comment by ValWood** [comment]
In fact, these are obviously names in the Broad contigs, therefore the ones that are not 'hypothetical proteiin' must be in the broad orthology table. We could add the broad orthologs to the Compara ones to increase the coverage. hopefully the 2 will cover more, and both should be accurate (the broad even more so if they used synteny). They clearly made quite different calls and missed different things.

Then I only need to do what is left......

**Comment by ValWood** [comment]
this one is out of date.  I have now annotated the products on everything except some of the species specific, which will include the missing orthologs. This  will be covered in other tickets.
