### ISSUE TITLE
Query builder: hide contigs with no genes?

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-config#25]
Some of the smaller japonicus contigs from GenBank have no genes.  Should we remove them from drop-down in the "Genome location" search section of the query builder?  Or we could grey them out.

Only 19 contigs out of 33 have genes annotated.

**Comment by kimrutherford** [comment]
Also perhaps we shouldn't say "Choose a chromosome" for japonicus since they're only parts of chromosomes?

**Comment by kimrutherford** [comment]
> hide contigs with no genes?

I went ahead and made this change.

We now have chromosomes and contigs in the menu so I'm not sure what to do about this question:

> Also perhaps we shouldn't say "Choose a chromosome" for japonicus since they're only parts of chromosomes?

**Comment by ValWood** [comment]
We  should maybe check if they have transposons or ribosomal RNAs or something....

**Comment by kimrutherford** [comment]
> We should maybe check if they have transposons or ribosomal RNAs or something....

Although those don't show up in the results table - it's only genes.

**Comment by ValWood** [comment]
I think we can, but we should wait until we are sure that some. of the missing RNAs mentioned here https://github.com/japonicusdb/japonicus-config/issues/39
s do not reside in these unannotated fragments. It's weird to have big segments with nothing coding in them....

**Comment by ValWood** [comment]
@snezhkaoliferenko  do you know what the  small contigs without genes are. Are they  enromere fragments?

**Comment by snezhkaoliferenko** [comment]
I don't sorry! was not involved in genome sequencing. off-hand (i don't have time to look it now) - do they have transposons on them? then could be centromeric.


________________________________

**Comment by ValWood** [comment]
No worries, I thought you might have come across them in searchers. There is no hurry and we can dig deeper into this  at  some point...
