### ISSUE TITLE
Don't transfer  NOT annotation from pombe , and don't transfer annotation to japonicus if a NOT is present

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-config#29]
I forgot this bit from #11:

> Also do not import for any gene/aspect with a NOT annotation (we need to make sure the japonicus community know if they use a NOT they need to make all annotations they intend to keep manually.

Here's an example where it's currently wrong: http://japonicusdb.kmr.nz/gene/SJAG_01143

![broken-not-annotation-inference-1](https://user-images.githubusercontent.com/90474/122218731-d546c000-cf02-11eb-8f90-f50121d24993.png)

**Comment by kimrutherford** [comment]
Will a NOT annotation ever have an extension?  If so, does that make a difference for transferring other annotation?

**Comment by kimrutherford** [comment]
Should we be transferring NOT annotations from pombe to japonicus?
(We are at the moment)

**Comment by kimrutherford** [comment]
> Also do not import for any gene/aspect with a NOT annotation

Hi Val.  I just want to check so I'm clear what you mean by "gene/aspect".

Do you mean, for example, don't import any BP annotations for mid1 because there is a BP NOT annotation?  Or should it be more specific: don't import any "mitotic cytokinesis, site selection" annotations from pombe because there is a japonicus NOT "mitotic cytokinesis, site selection" annotation?

**Comment by ValWood** [comment]
The plan is not to transfer any NOT annotations (pombe to japonicus) full stop.
NOT annotations are only used very rarely,  when an expected MF/BP/CC does not occur.
This makes them dangerous to transfer, even between close species.

If NOT annotation are applicable and helpful to japonicus they need to be added manually by the community to the GO GAF config  file (tangent I did not test this file yet btw, it is on my TODO list).

My thinking wasn't very clear when I opened this ticket. I think we can transfer the annotations which don't have a NOT. Any problems with these can. be. dealt with by filtering and annotation.
That should make this simpler to implement?

**Comment by ValWood** [comment]
The other way around, if a NOT annotation is made in japonicus, the corresponding annotation from PomBase should not be transferred. However, you seem to have done that already? http://japonicusdb.kmr.nz/gene/SJAG_01143

**Comment by ValWood** [comment]
> Will a NOT annotation ever have an extension? If so, does that make a difference for transferring other annotation?

It shouldn't. We can't currently negate specific extensions, so there do not need to be specific rules for extensions.

**Comment by kimrutherford** [comment]
> The plan is not to transfer any NOT annotations (pombe to japonicus) full stop.

That's fixed too now.
