### ISSUE TITLE
Permanent domain name: www.japonicusdb.org?

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-config#31]
We should decide on a permanent domain name.

I think "www.japonicusdb.org" is sensible (and it's available) but it could easily be japonicusdb.crick.ac.uk or japonicusdb.kcl.ac.uk if that was appropriate and supported by either institution.

I wonder if the Crick or KCL could register the name and look after that for us?  It would be one less ongoing thing we need to do.

**Comment by mah11** [comment]
> I think "www.japonicusdb.org" is sensible

I agree

**Comment by ValWood** [comment]
Snezhka to ask King/Crick to register the required domain name(s).

**Comment by kimrutherford** [comment]
Done!  http://www.japonicusdb.org/   and http://japonicusdb.org/

Thanks Snezhka!

It's still running on our server in Biochemistry but that's fine for now.

**Comment by snezhkaoliferenko** [comment]
amazeballs! @kimrutherford

**Comment by mah11** [comment]
Silly question: will the `https://` versions also work (now or soonish)?

**Comment by kimrutherford** [comment]
> will the https:// versions also work (now or soonish)?

I think we should be able to do that soonish.  We need to decide if we should host JaponicusDB at Babraham or on oliver1.  It's currently on oliver1 and my preference at the moment is to keep it there as it's easier for me.

If we keep it on oliver1 I can set up HTTPS versions quickly using "Let's Encrypt" (https://letsencrypt.org/) which is what we do for curation.pombase.org and what I do for kmr.nz.  If we host at Babraham we'll need to ask them to buy a certificate and to help configure it.

Let's decide on Thursday.

I made an issue about this #52
