### ISSUE TITLE
Make the PomBase slim labels display on gene pages:

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#33]
<img width="688" alt="Screenshot 2021-07-06 at 19 29 05" src="https://user-images.githubusercontent.com/7359272/124649592-9ae09b00-de90-11eb-9ac9-a10a134c0244.png">

**Comment by kimrutherford** [comment]
Done!

**Comment by kimrutherford** [comment]
> Done!

Er, I've just realised that I only enabled the labels for BP.  I'll fix that.
