### ISSUE TITLE
include human orthologs

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#34]
Can use Compara + any  transfer human ortholog of a pombe ortholog

**Comment by kimrutherford** [comment]
If japonicus -> pombe is many-1 and pombe ->human  is 1-many does that make japonicus -> human many-many?

(There are other combinations that I need to get straight in my head but I thought I'd just pick one for discussion)

**Comment by ValWood** [comment]
> If japonicus -> pombe is many-1 and pombe ->human is 1-many does that make japonicus -> human many-many?

yes ;)

**Comment by kimrutherford** [comment]
Oh dear.  I'll need to get my thinking head on and I've misplaced it.  :-)

**Comment by ValWood** [comment]
We could start with the 1:1s. These are the most valuable.
Then many:1 and 1:many.

For many to many we might want to be a bit more conservative, or restrict to the ribosomal and histones. I will need to check them.

**Comment by kimrutherford** [comment]
> We could start with the 1:1s. These are the most valuable.

OK.  I'll do that first.

**Comment by kimrutherford** [comment]
Can we use this file from the nightly load:
  https://curation.pombase.org/dumps/latest_build/pombase-build-2021-07-11.human-orthologs.txt.gz
to get the human-pombe orthologs?

It has the advantage that it's updated automagically when you update the orthologs in PomBase.

**Comment by ValWood** [comment]
Yes that makes sense.
We will need to fill in later with orthologs for japonicus genes conserved to human but not in pombe.
I only saw a few of these, but there could be more as I only spotted these because pombe didn't have a family member at all.

SJAG_00673 | bio3 | 7,8-diamino-pelargonic acid aminotransferase (DAPA) | fission yeast gene loss
SJAG_01739 |   | Dynactin subunit 4 | fission yeast gene loss
SJAG_00124 |   | NRG1-like trancriptional repressor, zinc finger C2H2-type | fission yeast gene loss

**Comment by ValWood** [comment]
But your way makes most sense becasue that will pick up all the distant orthologs missed by Compara.
I will add the human orthologs to the ones I spotted above. We can have a manual file like the
japonicus-pombe one?

**Comment by ValWood** [comment]
@snezhkaoliferenko might be interested in the broadly conserved.

**Comment by ValWood** [comment]
..missing from, fission yeast but present in japonicus and conserved to Metazoa. Sorry I went off to fix something mid-ticket and forgot what I was typing :)

**Comment by kimrutherford** [comment]
Now I've had a think about it, would it be OK to do a one-off mapping of human to japonicus genes?  That's less work than setting things up to re-map every load.  If the orthologs are eventually going to come from PAINT/Panther then maybe it makes sense not to spend a lot of a time on automating things?

My plan would be to create a human-japonicus orthologs file that will be checked-in and can be edited as needed.

> We can have a manual file like the japonicus-pombe one?

Yep!  We could have a separate file that gets all the newly spotted orthologs, or they could be added to the main human-japonicus orthologs file above.

**Comment by ValWood** [comment]
> My plan would be to create a human-japonicus orthologs file that will be checked-in and can be edited as needed.

That would work. We can make manual additions when we identify new ones.

I don't think we intended to get orthologs from PANTHER (they will probably have frewerr than we would start with). My hope is that  we can get GO inference vi PAINT using this. It seems unlikely though from discussions that japonicus will be included any time soon. The suggestion was to use a system called TREE grafter ? which allows people to  leverage the PAINT system for annotation transfer. Unless we were planned to PAINTIN all fungi this seems like a bit of a sledgehammer to crack a nut.

**Comment by mah11** [comment]
> ..missing from, fission yeast but present in japonicus and ...

I know this is off on a tangent and pedantic, but, well, it's what I do (@snezhkaoliferenko, better get used to it :wink:): If it's present in japonicus, it's not "missing from fission yeast" because japonicus IS a fission yeast.

**Comment by ValWood** [comment]
Drat, I thought I had fixed that. Maybe it was  the previous comments that I edited.
Feel free to correct me every time I say fission yeast  in this context.

**Comment by kimrutherford** [comment]
The human orthologs are now in the database and on the website.

The orthologs file is here: https://github.com/japonicusdb/japonicus-curation/blob/main/human_orthologs.tsv

**Comment by ValWood** [comment]
Awesome! @snezhkaoliferenko

**Comment by kimrutherford** [comment]
Is there anything else to do here?

**Comment by ValWood** [comment]
Nope, the rest is just tweaking and that is on the curation tracker.
v
