### ISSUE TITLE
include  human disease mappings, and MONDO slim

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#35]
automatically transfer from pombase once
https://github.com/japonicusdb/japonicus-config/issues/34
is done.

**Comment by ValWood** [comment]
This could be a follow up after release. After all we only had this recently for pombe

**Comment by kimrutherford** [comment]
> automatically transfer from pombase once #34 is done.

I don't think we need to wait for #34 because the MONDO terms are annotated on the pombe genes.  So they can be transferred using the pombe-japonicus orthlogs.

**Comment by ValWood** [comment]
True!
