### ISSUE TITLE
Apply PomBase GO filters to japonicus

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#38]
We filter obvious errors, and report them back to the provider.
All Pombase filters should apply.

pombe-embl/goa-load-fixes/
filtered_mappings 
filtered_GO_IDs 

Test
http://japonicusdb.kmr.nz/gene/SJAG_03360
GO:0019746 | hopanoid biosynthetic process | IEA with IPR006400
should disappear as 

 IPR006400 is currently a filtered mapping

A test for GO ID is 
GO:0007118
GO:0007114
http://japonicusdb.kmr.nz/term/GO:0007114

**Comment by kimrutherford** [comment]
>  All Pombase filters should apply.

Will you every need to add japonicus specific IDs for filtering?

**Comment by kimrutherford** [comment]
> All Pombase filters should apply.

I made that change and re-loaded.

> GO:0019746 | hopanoid biosynthetic process | IEA with IPR006400
> should disappear

That seems to be gone now.

**Comment by ValWood** [comment]
Fab!

**Comment by ValWood** [comment]
I was going to filter these (some many to many where there is specific annotation that we would not want to transfer)>

However, there is not GO annotation transferred from orthologs for these.
(I am looking for examples to check that I can filter on. pattern matches to Pombe and S. cerevisiae gene IDs..)

**Comment by ValWood** [comment]
Question for Kim.

**Comment by kimrutherford** [comment]
Sorry, what is the question?

**Comment by ValWood** [comment]
I think this is a duplicate ticket. Filters are implemented apparently.
