### ISSUE TITLE
Canto configuration

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#4]
Canto text for gene input:

Please list the genes studied in this paper using the systematic identifier (eg. SPCC1739.10) or standard name (eg. cdc11) separated by commas, spaces, tabs or one per line.

change for a S. japonicus systematic identifier and an example named gene (one of Snezhana's!).

**Comment by kimrutherford** [comment]
> one of Snezhana's

Can you give me an example?

**Comment by ValWood** [comment]
This one would be good PMID:25866389

**Comment by kimrutherford** [comment]
> This one would be good PMID:25866389

Did you mean a specific gene from that paper or will any of them do?

**Comment by ValWood** [comment]
Ah sorry, I  forgot what this ticket was about. In this case any japonicus systematic ID will work -we can use mid1. I can't access japonicusDB right now.

**Comment by kimrutherford** [comment]
> In this case any japonicus systematic ID will work -we can use mid1.

OK, thanks.  I've changed the configuration.

> I can't access japonicusDB right now.

It's working for me.  What error do you get?  Can you access dev.pombase.kmr.nz?  That's on oliver1 too.  (So is Canto)

**Comment by ValWood** [comment]
It is working again now...

**Comment by kimrutherford** [comment]
> It is working again now...

What was the error?

**Comment by ValWood** [comment]
I can't remember precisely.
It was the blank page with  some single line text with something like "cannot access url..."
