### ISSUE TITLE
add commonly used queries

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#41]
Please add commonly used queries for
1) all Proteins with human orthologs
2) all Proteinswith a human disease gene mapping
3) all Proteins with pombe orthologs
4) all Proteins with S. cerevisiae orthologs

...because we aren't going to do taxonomic conservation malarky it is not possible to access these lists via normal queries.

**Comment by kimrutherford** [comment]
Querying for the existence of an ortholog will need some changes to the query system.  It's not a huge job but it's not implemented yet.

> all Proteins with a human disease gene mapping

For that one we'll need to wait until we have mapped across the disease associations from pombe to japonicus.

**Comment by ValWood** [comment]
> until we have mapped across the disease associations from pombe to japonicus.

whoops, I thought I saw the disease slim yesterday. Must have been on the wrong front page!

**Comment by ValWood** [comment]
If possible I would like to get a list of all proteins which do not have a pombe ortholog, but which do have a S. cerevisiae ortholog.
Ican't think of an easy way to do this without the querying above enables, but if you could extract such a list  with aSQL query that  would allow  me to check the GO annotation. No hurry for this.

**Comment by kimrutherford** [comment]
You should be able to do that in QuiLT by selecting the genes without a pombe ortholog, then unselecting those without a cerevisiae ortholog.

**Comment by ValWood** [comment]
I forgot you already told me that!

**Comment by ValWood** [comment]
The GO annotation coverage is looking pretty amazing. I'm done with that part....

**Comment by ValWood** [comment]
...I meant to say Quilt was really brilliant for this interactive filtering. I don't often use it like that.

**Comment by kimrutherford** [comment]
> I meant to say Quilt was really brilliant for this interactive filtering. I don't often use it like that.

:-)

It's quite a fun way to do filtering but I think pombase/website#1729 will be very useful too.  I don't think it is needed for release but I think it's a useful feature to add quite soon.

**Comment by kimrutherford** [comment]
> If possible I would like to get a list of all proteins which do not have a pombe ortholog, but which do have a S. cerevisiae ortholog

I think that's now this query:
https://www.japonicusdb.org/results/from/id/563498cf-e74c-4c39-b760-8946e5145e67

**Comment by kimrutherford** [comment]
I've added the three commonly used queries for orthologs but I've just noticed that I've ignored your suggested descriptions (like "all Proteins with human orthologs").  I used "Genes with human orthologs".  It's easy to change.  Which do you prefer?

**Comment by ValWood** [comment]
Proteins  is clearer becasue we only consider protein, we haven't curated orthologs for any non protein-coding genes (and non of thee predictors cover ncRNAs either)

**Comment by ValWood** [comment]
This is very cool though....

**Comment by kimrutherford** [comment]
OK. I've changed the text and it will be visible in the morning.

Should we also change "All protein coding genes" to "All proteins" for consistency?

**Comment by ValWood** [comment]
I don't know which wording is clearest, but we should use the same on both sites
https://www.pombase.org/query

**Comment by ValWood** [comment]
OK,  done here. we don't have a query for disease genes, but we don't have that yet anyway so that can be part of the 'disease' ticket (non existant)

**Comment by kimrutherford** [comment]
> OK, done here.

Yep, but it would be nice to have one or two more commonly used queries.  And for PomBase too.

**Comment by ValWood** [comment]
I can't think of any immediately, we go pretty quickly from general queries to very specific....

**Comment by ValWood** [comment]
We can add a "conserved in japonicus" to pombe

**Comment by kimrutherford** [comment]
> We can add a "conserved in japonicus" to pombe

Good plan.  I've added the configuration and it will be visible tomorrow.
