### ISSUE TITLE
Add reciprocal links to japonicus from PomBase ortholog section

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#45]
Using  the same ortholog calls as used for japonicus, add japonicus orthologs to  PomBase ortholog section.

**Comment by kimrutherford** [comment]
> Using the same ortholog calls as used for japonicus, add japonicus orthologs to PomBase ortholog section.

Should be easy once we have `japonicusdb.org` working.  But it would be best if we could add JaponicusDB/japonicusdb.org to the GO xrfs file so we don't have to have our of local config for it.

**Comment by mah11** [comment]
>  it would be best if we could add JaponicusDB/japonicusdb.org to the GO xrfs file

I've opened #46 to remind me to make that happen. I'll act on it when japonicusdb.org is up and chugging (#31).

**Comment by ValWood** [comment]
I think we should display these on the day we go live.
Which I guess is:
hosting on new domain
Updated docs
footer fodder
NOT GO annotation
functioning mailing list (although this could be a follow up to release)
everything else can be incremental, and we can announce as we go

**Comment by kimrutherford** [comment]
> I've just made the changes needed to load the japonicus IDs and pombe-japonicus orthologs into PomBase Chado. I'm doing a local test now and it should be in the main PomBase database in the morning.

Sorry, due to forgetting to commit one of the changes, I broke the load.  It's fixed for tomorrow.
