### ISSUE TITLE
ortholog transfer of names missing

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#47]
some 1:1 japonicus:pombe ortholog names are not transferred automatically.

For example:
http://japonicusdb.kmr.nz/gene/SJAG_05309

(that is the only one I came across, I wonder if there are more??)

**Comment by kimrutherford** [comment]
It's not 1-1: spo15 (SPAC1F3.06c) is an ortholog of SJAG_05309 and SJAG_05310.

**Comment by ValWood** [comment]
Right, oops I thought I already did all of those!
