### ISSUE TITLE
citation for orthologs

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#50]
Our ortholog calls have:
Schizosaccharomyces pombe | SPBC21B10.15 | Schizosaccharomyces specific protein | Rhind N et al. (2011)

Should be unpublished and I will replace later by the japonicus paper.

**Comment by kimrutherford** [comment]
I've fixed the reference in the load script and I've started a new load.  It will be fixed on the site in an hour or so.

**Comment by ValWood** [comment]
super, wasn't urgent ;)
