### ISSUE TITLE
Re-calculate japonicus-human orthologs each load

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#54]
http://japonicusdb.kmr.nz/gene/SJAG_07017
Does not have human ortholog

I'm not sure why as I'm assuming these are pulled through to japonicDB from the pomb-human connection?

**Comment by kimrutherford** [comment]
The japonicus-human orthologs are not yet recomputed each load.  I ran a script to create this file: `japonicus-curation/human_orthologs.tsv` and that's what gets loaded.  SJAG_07017 isn't in the file.

I forgot to come back to this and make it recompute every load.  I'll do that next.

**Comment by ValWood** [comment]
Right I forgot that was a. more recent one.

I still think PomBase should take precedence ...

**Comment by kimrutherford** [comment]
> I still think PomBase should take precedence ...

I don't understand that.  Could you explain?

**Comment by kimrutherford** [comment]
> I forgot to come back to this and make it recompute every load. I'll do that next.

I've made the changes.  I'm doing a test load now.

**Comment by kimrutherford** [comment]
SJAG_07017 has a human ortholog now.  The orthologs will update every night from now on using the pombe-human orthologs from the PomBase nightly load and the current japonicus-pombe orthologs.

Please let me know if you spot any other problems.
