### ISSUE TITLE
configuration for phenotype?

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#55]
M do you know how to fix?

failed test: Check that all phenotype terms have a parent in one of the categories in the website 

from the logs:

configuration for fission_yeast_phenotype
  FYPO:0007773	PMID:27678009	abnormal hyphal growth [has_severity] medium	1
  FYPO:0007778	PMID:31150379	decreased hyphal branching [has_severity] high	1
  FYPO:0007776	PMID:31150379	decreased hyphal length	1
  FYPO:0007776	PMID:31150379	decreased hyphal length [has_severity] high	1
  FYPO:0007780	PMID:31150379	decreased mycelial expansion	1
  FYPO:0007780	PMID:31150379	decreased mycelial expansion [has_severity] high	1
  FYPO:0007777	PMID:31150379	increased hyphal branching	1
  FYPO:0007777	PMID:31150379	increased hyphal branching [has_severity] medium	1
  FYPO:0007775	PMID:31150379	increased hyphal length [has_severity] high	2
  FYPO:0007774	PMID:31150379	increased invasive hyphal growth [has_severity] high	2
  FYPO:0007779	PMID:31150379	increased mycelial expansion	2
pombe_genes - SUCCESS

**Comment by mah11** [comment]
Which log is this from?

Yes, I think I know how to fix it. But I'll need to know whether you or @snezhkaoliferenko want these phenotypes grouped with cell phenotypes or population phenotypes on the web pages.

**Comment by ValWood** [comment]
https://curation.pombase.org/japonicus_nightly/latest_build/logs/log.2021-08-10-06-32-18.chado_checks

We have this problem with PHIPO too for these types of phenotype. It's tricky.

We could put them under cell for now but I wonder if for japonicus we change the label of the cell section to be  "Single organism-level phenotype". Maybe too clunky? it is more accurate...

**Comment by mah11** [comment]
I don't have a strong preference, so just let me know what you and S decide and I'll edit the config accordingly.

**Comment by snezhkaoliferenko** [comment]
Organism-level?

**Comment by mah11** [comment]
OK, I've changed the display text to "Organism-level", so it'll accommodate the hyphal terms. We can reopen this if anyone thinks of anything better.
