### ISSUE TITLE
add japonicusDB: to GO xrefs?

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#56]
with' values that have an unsupported DB prefix - CHECK FAILURE:  expected 0 but got 3
  JaponicusDB	34571f3accd180c4	PMID:23337086
  JaponicusDB	e134ba05c345c3f5	PMID:32243490
  JaponicusDB	fb189c5ef542852c	PMID:26343758

**Comment by kimrutherford** [comment]
I've added JaponicusDB: to the Chado check

**Comment by kimrutherford** [comment]
This warning is gone this morning.
