### ISSUE TITLE
Transfer pombe gene synonyms to japonicus

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-config#57]
From: https://github.com/japonicusdb/japonicus-config/issues/12#issuecomment-896608947

**Comment by ValWood** [comment]
except systematic IDs

**Comment by ValWood** [comment]
Lets not do this.
It will just propagate old, unused names, lots of conflicting names, allele names etc..

Useful synonyms can be added manually as requested. For instance, I will add cdk1 for cdc2.  @snezhkaoliferenko  which do you want to be the primary name for cdc2? It could be cdk1 with cdc2 as a synonym. You have the power!

If it becomes a pain and japonicus people want PomBase synonyms adding globally  we can add them later.

**Comment by ValWood** [comment]
Scrub the above about manually adding synonyms. Once we do that we need to maintain the products manually too. We don't want to do this. 
Later we can decide whether to import all PomBAse synonyms, but for now, no action.
