### ISSUE TITLE
Add to mini ontology?

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#58]
I'm guessing that this is a configuration issue?

no SO type for mobile_element - skipping
no SO type for mobile_element - skipping
no SO type for mobile_element - skipping
no SO type for mobile_element - skipping

**Comment by kimrutherford** [comment]
The contig loader needs changing to accept mobile_element features.  It's a quick fix.

**Comment by kimrutherford** [comment]
I think this problem went away when fixing japonicusdb/japonicus-config#28
