### ISSUE TITLE
SJAG_06638 product

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#59]
I have been trying to troubleshoot this one for a few days.

SJAG_06638 product doesn't appear
but it seems OK in the ortholog file

manual_pombe_orthologs.tsv:SJAG_06638	SPMTR.01

I can't see anything in the logs. Any ideas?

**Comment by kimrutherford** [comment]
I think the problem is that SPMTR.01 has two orthologs, one manual and one from Compara:

./manual_pombe_orthologs.tsv
4:SJAG_06638    SPMTR.01

./compara_pombe_orthologs.tsv
14:SJAG_01113   SPMTR.01

**Comment by ValWood** [comment]
So if i remove 
14:SJAG_01113 SPMTR.01
from Compara and add to
manual_pombe_orthologs.tsv will that work?

**Comment by kimrutherford** [comment]
You'd still have two orthologs for SPMTR.01 so the transfer wouldn't happen.

The only way around this is to add the name and products of SJAG_06638 and SJAG_01113 to the names_and_products file.
