### ISSUE TITLE
Change image on 'recent community curation' panel

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#61]
We can use  the Canto logo for now maybe,

but if we have a Japonicus stats page we can screenshot the histogram.

**Comment by kimrutherford** [comment]
> We can use the Canto logo for now maybe,

I've changed the image.

**Comment by kimrutherford** [comment]
> but if we have a Japonicus stats page we can screenshot the histogram.

It's fixed now.  Do you think it would look OK?:
https://curation.pombase.org/japonicus/stats/annotation

**Comment by ValWood** [comment]
Maybe we will just leave the Canto logo, at least for now...
