### ISSUE TITLE
japonicus characterization status

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#62]
I didn't think we had this for japonicus,  as it comes from the 'colour' qualifier in PomBase and we don't use that.
.....but I just noticed that a new gene qcr10 has characterization status 'dubious'. Where does that come from?

**Comment by kimrutherford** [comment]
I can't see "dubious" on the gene page for qcr10.  Where did you see it?

**Comment by ValWood** [comment]
I'm sure I saw it in the "characterization status field in the. header, but now it is empty. I'm sure I didn't image it though!
