### ISSUE TITLE
curation date on stats page

### ISSUE THREAD

**Issue by mah11** [japonicusdb/japonicus-config#63]
Is this a bug? The japonicus curation stats have sensible dates in the data tables, but the graphic has them all piled up in the <2004, 2004, and 2005 columns. It looks odd.

https://curation.pombase.org/japonicus/stats/annotation

**Comment by mah11** [comment]
To clarify: it's the first graphic that looks wrong. The rest of the charts look OK.

**Comment by mah11** [comment]
... While I'm on that page: it's also still got the PomBase name and logo, and in the text some occurrences of "PomBase" haven't been changed to "JaponicusDB".

**Comment by kimrutherford** [comment]
I'll fix the bug and change the name and logo.

**Comment by kimrutherford** [comment]
Note to self: after fixing this, have a look at: https://github.com/japonicusdb/japonicus-config/issues/61#issue-970440428

**Comment by kimrutherford** [comment]
Fixed!
