### ISSUE TITLE
News item 

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#64]
News item 

A comprehensive genome annotation review has identified 17 new protein-coding genes, revised 36 gene structures and deleted 8 gene predictions.  All protein-coding gene product descriptions have been updated, improved and standardized.

**Comment by mah11** [comment]
done

**Comment by mah11** [comment]
p.s. in this commit https://github.com/pombase/website/commit/a1ee887c296a0dd72453b4e40f42db8d3a4aaf3c
