### ISSUE TITLE
Fix link to mailing list in menu

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-config#66]
It currently points to pombelist.

**Comment by ValWood** [comment]
@snezhkaoliferenko  what is the mailing list URL?

**Comment by mah11** [comment]
`https://mailman.kcl.ac.uk/mailman/listinfo/japonicus-list`

it's also already in the markdown file for the "community" main page but I haven't mucked with any menus on the left-hand sides of pages, let alone in the menu bar (far less risky to leave that to @kimrutherford ;)

**Comment by kimrutherford** [comment]
The mailing list link is now configurable with the new "community_mailing_list" setting.  And JaponicusDB now has the correct link in the menu.
