### ISSUE TITLE
remove esyN icons and related text

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#68]
We won't configure this for japonicus. It is really only a "placeholder" network view, and there won't be enough curated causal connections for japonicus to make it meaningful.

Icons beside each GO term link to esyN, which provides a graphical view of interactions for the genes from the JaponicusDB High Confidence Physical Interaction Network (HCPIN) dataset. Only the subset of genes linked into the interaction network will be displayed in the esyN network view. The annotation totals link to pages with information about the term and a list of annotated genes.

(it might be in the todo list. for documentation , but I thought I would mention it)

**Comment by mah11** [comment]
actually, this answers a question I had about which bits of documentation were database-specific ;)

**Comment by kimrutherford** [comment]
I can see the icons here:
  - https://www.japonicusdb.org/browse-curation/fission-yeast-bp-go-slim-terms

and here:
  - https://www.japonicusdb.org/term/GO:0030036

Is there anywhere I've missed?

**Comment by ValWood** [comment]
I can't think of anywhere else....

**Comment by kimrutherford** [comment]
OK, thanks.  I've fixed those two pages.

**Comment by kimrutherford** [comment]
Sorry, I forgot that there's documentation to fix.

**Comment by mah11** [comment]
I've updated the documentation in https://github.com/pombase/website/commit/a450e10ad9f709321879f1b62ceae007669afce2
