### ISSUE TITLE
Add link to AmiGO in external links section

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#7]
I think the following external links will work with uniprot IDs:

~quickGO~
~ensembl~
~ncbi~
~string~
amigo  (not worth adding yet as they won't be in amigo, we will get them included as a MOD at some point)

**Comment by kimrutherford** [comment]
> I think the following external links will work with uniprot IDs:
>
> ensembl

Ensembl seems happy with the japonicus IDs.  Is there an advantage to changing?

**Comment by ValWood** [comment]
no, sorry, I was moving some old notes to the tracker. I don't think Ensembl links were there when I made the list. Japonicus IDs are better here.

**Comment by kimrutherford** [comment]
No problem.  I was surprised but the japonicus IDs work fine when linking to Ensembl.

**Comment by kimrutherford** [comment]
I've added links to QuickGO and STRING.

> amigo (not worth adding yet as they won't be in amigo, we will get them included as a MOD at some point)

I'll leave the issue open until we can add that.

**Comment by ValWood** [comment]
Since the GO submission is going to happen  fairly soon, you can add the AmiGO link in anticipation and close this if you like.

**Comment by kimrutherford** [comment]
OK, I've done that.
