### ISSUE TITLE
text for funding

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#71]
Change acknowledgement text under about to

 'Wellcome Trust Senior Investigator Award [103741/Z/14/Z] to Snezhana Oliferenko'

**Comment by ValWood** [comment]
Probably @kimrutherford needs to do this as part of footer,]?

**Comment by mah11** [comment]
I'll update the About page tomorrow. This level of detail should not go in the footer.

**Comment by ValWood** [comment]
I forgot this isn't in the footer, I was thinking about 2 different things. I mean the 'About' page.

**Comment by mah11** [comment]
done
https://github.com/pombase/website/commit/c445613a2b15a5b7ff30753d56fcad6838628694
