### ISSUE TITLE
Supplement PomBase S. cerevisiae  ortholog predictions with Compara

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#72]
Supplement PomBase S. cerevisiae  ortholog predictions with Compara
( same as  pombe & human)

I will block the mispredictions later. I'm working through the pombe ones now...

**Comment by kimrutherford** [comment]
Sorry!  After commenting on the Google Doc I realised that we're doing this already.  It's the human orthologs that we don't do this for because Compara doesn't provide human<->japonicus orthlogs as far as I can tell.

**Comment by ValWood** [comment]
Yup it says  pan-taxonomic Compara not available?
OK.
