### ISSUE TITLE
JaponicusDB2UniProt

### ISSUE THREAD

**Issue by mah11** [japonicusdb/japonicus-config#74]
Is there a file equivalent to [PomBase2UniProt.tsv](https://www.pombase.org/data/names_and_identifiers/PomBase2UniProt.tsv), or a plan to produce one?

I thought of asking so I know whether to make the link on the names-and-identifiers page PomBase-specific (per #3), but it seems like a good file to produce.

**Comment by ValWood** [comment]
Seems like a good plan to produce...

**Comment by mah11** [comment]
related: also produce allNames.tsv and maybe pseudogeneIDs.tsv (is the latter relevant for S.j.?)

and some other files in other data/subdirectories listed in https://github.com/japonicusdb/japonicus-config/issues/78#issuecomment-912640639

**Comment by kimrutherford** [comment]
> Is there a file equivalent to PomBase2UniProt.tsv, or a plan to produce one?

I've changed the nightly script to copy the uniprot mapping file to https://www.japonicusdb.org/data/names_and_identifiers/JaponicusDB2UniProt.tsv

I'll check that tomorrow.

> related: also produce allNames.tsv and maybe pseudogeneIDs.tsv (is the latter relevant for S.j.?)

Could you point me to allNames.tsv for pombe?  I can't find it.

**Comment by mah11** [comment]
> Could you point me to allNames.tsv for pombe? I can't find it.

On the web it winds up at
https://www.pombase.org/data/names_and_identifiers/allNames.tsv

But it's not in pombe-embl/ftp_site/pombe/names_and_identifiers/, so I don't know how it comes into existence. It does have a current date/time stamp ...

**Comment by kimrutherford** [comment]
> On the web it winds up at
> https://www.pombase.org/data/names_and_identifiers/allNames.tsv

I've worked this out.  This file is just a symbolic link to: https://www.pombase.org/data/names_and_identifiers/gene_IDs_names.tsv

I've now created the same link for japonicus: https://www.japonicusdb.org/data/names_and_identifiers/allNames.tsv

**Comment by mah11** [comment]
I'm not sure whether I forgot that, or never knew it in the first place. Yay, though :)

**Comment by kimrutherford** [comment]
I think this is done now.
