### ISSUE TITLE
Hide "Characterisation status"?

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-config#76]
The genes pages have a blank "Characterisation status" field.  Should we hide it for japonicus?

**Comment by ValWood** [comment]
yep, please. no hurry...

**Comment by ValWood** [comment]
Still need to remove the text "Characterisation status" for now.
I thought  you did that?

**Comment by kimrutherford** [comment]
> I thought you did that?

I haven't got around to it yet.

**Comment by kimrutherford** [comment]
I've made this change.  It will be visible on Wednesday morning.  I'll check and close the issue then.
