### ISSUE TITLE
add icons for mailing list, twitter, Git, 

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#77]
<img width="492" alt="Screenshot 2021-09-01 at 14 19 03" src="https://user-images.githubusercontent.com/7359272/131696248-cf9475a5-1b89-4ae8-9992-76fd2fb96983.png">

**Comment by kimrutherford** [comment]
Good plan.  It will look like this in the morning:
![jdb-social-1](https://user-images.githubusercontent.com/90474/131770227-8b7e9381-ec9f-4a4f-bfbd-7d2d96e3e594.png)
