### ISSUE TITLE
Create a new "original load japonicus slim"

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#79]
Create an "original load japonicus slim"
pre filtering (using filtered GO terms, but not filtered mappings).
(as discussed today)

**Comment by kimrutherford** [comment]
> pre filtering (using filtered GO terms, but not filtered mappings).

I ran a load like that and put it here:
  http://japonicusdb-goa.kmr.nz/vis/from/id/b3c8c004-adbd-4409-972a-1dda7eff46e8

It's on my desktop so it won't be available between 1pm and 8pm or so each day.

**Comment by ValWood** [comment]
OK, there is still a massive increase for each aspect even if we use pre filtered for blocked mappings. It is reduced, especially for MF, but it. is still significant, and highly visible by eye. This is good because  although we could exclude some of the InterPro mappings which are still false positive, I  would not be able to do anything with the keywords and UniProtKB-SubCell which has a small % of false positives cover lots of entries.
So, go ahead with the figure using the pre-filtered data. It will still look good.

**Comment by kimrutherford** [comment]
Here's how it looks with filtered GO terms, but without filtered mappings.  It's changed only a bit.  Please let me know which connecting lines to add or remove, or any other changes.

![quilt-comp-8-export](https://user-images.githubusercontent.com/90474/132119957-accb7307-63ec-44f6-96e6-d0bcbcb7a9fa.png)


Here's the SVG file:  [quilt-process-change-diagram-8.svg.gz](https://github.com/japonicusdb/japonicus-config/files/7111198/quilt-process-change-diagram-8.svg.gz)

**Comment by ValWood** [comment]
brilliant! I think where we filter KW mappings there will usually be InterPro.

I'm not going to use the biggest increases,  we will highlight some of the smaller , but more relevant ones.

Try
BP 
membrane organization
lipid metabolic process

CC
ER 
mitochondria (as  now)

MF
hydrolase
molecular adaptor activity (new)

then still connect the unknowns.

**Comment by kimrutherford** [comment]
> Try

I'll include those changes when I recreate the figure with the change from #1758.  I'll try that on Monday.

**Comment by kimrutherford** [comment]
> I think where we filter KW mappings there will usually be InterPro.

I don't understand that bit.

> I'm not going to use the biggest increases, we will highlight some of the smaller , but more relevant ones.

Have I got this right?:

![quilt-comp-11-export](https://user-images.githubusercontent.com/90474/132279801-c39b8c22-fd26-442a-b1d1-84f3f667509e.png)

**Comment by ValWood** [comment]
>>I think where we filter KW mappings there will usually be InterPro.
> I don't understand that bit.

I'm just pondering why the affect from using the pre-filtering data was not as large as Iexpected. You can ignore...

**Comment by ValWood** [comment]
Yes!
1. We can add the connection between BP gene expression because we do mention that in the legend
2. Remove "organelle localization" from the Quilt processes. Although it has ~175 annotations, it isn't a good slim classifier because most are also annotated to other more specific terms with higher precedence (this applies to Quilt generally)
3. Change the precedence of "generation of precursor metabolites and energy" so that. it comes immediately before "small molecule metabolic process". Most eneragy pathways will besucked up by this term so we don't see this change. Energy metabolism is important  (this applies to Quilt generally)-  add a connector here because this will grow (I hope)
 MF and CC,  no changes.

This looks great!

**Comment by ValWood** [comment]
revised  above comment

**Comment by kimrutherford** [comment]
Are changes 2-4 for the figure?  I'd rather not have to redo it again.

**Comment by ValWood** [comment]
They were, but they aren't critical....I can remove the mention of energy generation from the legend. I'm probably the only person on the planet who 2&3 will mean anything to, and they don't affect the results. So jut adding back the connection for gene expression then this one is done.

**Comment by kimrutherford** [comment]
That's a relief!  I'll add the gene expression connection a bit later this morning and post the result.

**Comment by kimrutherford** [comment]
How's this.  Anything need tweaking?  I'll export a high resolution version when we're ready to submit the manuscript.

![quilt-comp-12-export](https://user-images.githubusercontent.com/90474/132348075-83950313-e1d4-40ed-bf30-588f4a00e621.png)

[quilt-process-change-diagram-12.svg.gz](https://github.com/japonicusdb/japonicus-config/files/7121628/quilt-process-change-diagram-12.svg.gz)

**Comment by ValWood** [comment]
Looks perfect to me!

**Comment by mah11** [comment]
Very nice.

Genetics wants figures in PDF or EPS format (PDF is ever-so-slightly easier to use with LaTeX). Hint: when saving .pdf or .eps in Inkscape, DON'T tick "Rasterise filter effects".

**Comment by ValWood** [comment]
Fab!
