### ISSUE TITLE
Fix the publication used for the genome in the browser

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#8]
To PMID: 21511999

**Comment by kimrutherford** [comment]
I've committed a fix for this, but after I started the current load.  So the fix will be visible some time later.

For now the loads are started manually.  I'll set up nightly loads soon.

**Comment by kimrutherford** [comment]
I fixed the PMID but I then noticed that the author was still "Wood" in JBrowse.    Whoops.

I've committed a fix that will be visible next time I deploy.
