### ISSUE TITLE
Analysis to see  how many genes have "improved GO annotation depth"

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#80]
Will just be a binary improved/not improved per aspect/per gene.

We might display in a 3-way Venn.

As discussed today.

**Comment by kimrutherford** [comment]
I've had a go at this.  I found 4321 genes with at least one more specific annotation compared to GOA (with no mapping filter).

Here is the breakdown:

| aspects  | counts |
| ----- | ----- |
| BP       |   191 |
| BP,CC    |  1301 |
| BP,CC,MF |  1399 |
| BP,MF   |   161 |
| CC       |   836 |
| CC,MF    |   346 |
| MF      |    87 |

And here is the Venn diagram ready for publication:

![publication_ready_venn_diagram](https://user-images.githubusercontent.com/90474/132434501-15a50e03-4fad-435e-b5fe-81c4f2eb08f0.png)

This file has the per gene information:
[increased_annotation_depth_gene_and_cvs.tsv.txt](https://github.com/japonicusdb/japonicus-config/files/7125232/increased_annotation_depth_gene_and_cvs.tsv.txt)

**Comment by ValWood** [comment]
LOL! 
That's impressive! and pretty close to what I expected;)

I would only make one change to your lovely figure!
Can we also add outside the Venn  575 (the unchanged cohort).  Maybe we don't need to put 4321 outside because the *real* total is 4896. If we do we should somehow put all 3 numbers to make this clear.


i.e Title: S.japonicus proteins with more specific GO annotation for each aspect of GO.
Suggested legend:
Each of the S. japonicus proteins (4896) was assessed for improved annotation specificity (i.e. an annotation further from the root node in any branch), for each aspect of GO (MF, BB, CC). Improvements were observed for 4321 (>88%) proteins. For 1399 (>28%) proteins specificity was increased in all three GO aspects.

**Comment by kimrutherford** [comment]
I thought I'd try my hand at a tidier diagram.  I this a good start?  It's very easy to change.

![japonicus-paper-venn-1](https://user-images.githubusercontent.com/90474/132474273-7f825b12-8367-4208-b5f9-faa5577925c6.png)

**Comment by kimrutherford** [comment]
> Can we also add outside the Venn 575 (the unchanged cohort).

How should number be labelled?  Just "575 Unchanged"?

**Comment by kimrutherford** [comment]
![japonicus-paper-venn-2](https://user-images.githubusercontent.com/90474/132478548-11293e50-782a-4ed1-877d-c4dcf3f3f8f9.png)

**Comment by ValWood** [comment]
Yes.
Or should we put
Total: 4896
Changed: 4321

We don't need to put the 'unchanged' then. It's obvious.

**Comment by ValWood** [comment]
should we use 3 colours (this looks quite good colour choice)
https://www.nicepng.com/maxp/u2r5u2t4t4u2o0o0/
(will look nicer on slides)

**Comment by kimrutherford** [comment]
I've kept the borders so it will look OK if printed in black and white, but I think they're a bit wide and dark in this attempt.  What do you think?

I can remove the borders for putting in slides.

![japonicus-paper-venn-3](https://user-images.githubusercontent.com/90474/132483261-50b6ecac-2694-4c62-b9be-6c4ae13b748e.png)

**Comment by ValWood** [comment]
Slightly thinner borders, then this is ready to go ;)

**Comment by kimrutherford** [comment]
How's this?:

![japonicus-paper-venn-4](https://user-images.githubusercontent.com/90474/132491723-7533f707-3ad9-4389-b1f5-8788182b3705.png)

**Comment by ValWood** [comment]
Thumbs up from me!

**Comment by ValWood** [comment]
@mah11  may not be tracking this ticket.This is figure 3 unless you have suggestions.

**Comment by kimrutherford** [comment]
Here's the PDF version: [paper-venn-5.pdf](https://github.com/japonicusdb/japonicus-config/files/7128593/paper-venn-5.pdf)

**Comment by kimrutherford** [comment]
Needs re-doing.

**Comment by kimrutherford** [comment]
Here's the update:

![japonicus-paper-venn-5](https://user-images.githubusercontent.com/90474/133046122-d8a7e1d3-f5d4-46b9-b675-cc7e80a12720.png)

**Comment by kimrutherford** [comment]
Here are the numbers so you can check that I got the diagram right:

```
 BP,CC,MF    1385
 BP,CC       1282
 CC           862
 CC,MF        353
 BP           183
 BP,MF        153
 MF            94
```

**Comment by kimrutherford** [comment]
Here is the PDF:

[paper-venn-6.pdf](https://github.com/japonicusdb/japonicus-config/files/7153917/paper-venn-6.pdf)

**Comment by mah11** [comment]
Incorporated into the manuscript, so closing :)
