### ISSUE TITLE
FAQs which do not apply to japonicus

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#82]
Can I find all of the unconserved (orphan) genes in fission yeast?
Since we don't have taxonomic distribution.
It is possible to get an approximation using Queries though...

Can I get a list of essential japonicus genes?
(there is very little coverage)
Note that viability/inviability annotations are fairly complete for protein-coding genes, but very few non-coding RNA genes have been tested.

Can I get a list of systematic IDs, primary names, synonyms and gene products in S. japonicus?
mentions
https://www.pombase.org/data/names_and_identifiers/sysID2product.tsv

Can I search for genes based on conservation in different taxa?
Yes, use the “Taxonomic conservation” query in the advanced search.
Example query: Genes conserved in vertebrates

Can I search JaponicusDB for protein features?
None annotated.

Can I view variation data in PomBase?
Not applicable

How are non-coding RNA genes identified?
Not applicable:
Most non-coding RNAs in JaponicusDB are based on transcriptome data, either from Jürg Bähler’s lab (Solexa/deep sequencing; PMID:18488015) or Nick Rhind’s lab (RNA sequencing; PMID:21511999). For any ncRNA, the source should be linked as a publication in the “Literature” section at the bottom of the JaponicusDB gene page. To get an idea of the transcription in a region, you can look at the Bähler Lab Transcriptome Viewer, which is linked from most gene pages, e.g. SPNCRNA.200. Unfortunately some genes, such as SPNCRNA.1115, post-date the viewer and therefore do not have entries, but you can look at transcription in this region by finding a neighboring gene.

How are sequence feature types defined in JaponicusDB?
Not applicable
S. japonicus genome features were originally annotated using Artemis. As noted in the manual (ftp://ftp.sanger.ac.uk/pub/resources/software/artemis/artemis.pdf - see p. 9), Artemis draws from a list of feature keys that is documented at EBI: (ftp://ftp.ebi.ac.uk/pub/databases/embl/doc/FT\_current.html\#7.2\)
In the genome sequence data files, features are defined using Sequence Ontology terms. Gene pages use a selection of human-friendly text descriptions for feature types.

- [ ] How can I find GO annotations for other Schizosaccharomyces species?
We can delete this FAQ item from JaponicusDB AND PomBase, it was originally written for Snezhka! 

- [ ] We need a new  FAQ for this item; )
How can I find orthologs between S. japonicus and other Schizosaccharomyces species?
On a gene-by-gene basis, you can use the Ensembl genome browser link to reach Fungal Compara as described in the FAQ on orthologs in other species.
For a full set of orthologous genes in S. pombe, S. cryophilus, S.japonicus and S. octosporus, see Table S12, columns AD-AG, in Rhind et al. Comparative functional genomics of the fission yeasts (PMID:21511999).

How can I find S. japonicus orthologs for species other than human and S. cerevisiae?
We need a different FAQ for this, or delete for now. Most resources do not include japonicus

How many conserved unstudied proteins are there? How is the list generated?
Not applicable

Is there a list of protein complexes in S. japonicus, and their subunits?
Not applicable

What does the “characterisation status” mean for a gene?
Not applicable

**Comment by mah11** [comment]
> We need a new FAQ for this item:
> 
>> How can I find orthologs between S. japonicus and other Schizosaccharomyces species?

Please open a separate ticket for this, with the desired question and answer text. Also pls indicate whether there should be one FAQ to do for both PomBase and JaponicusDB, or separate FAQs (one per db).
 
I'll do any necessary polishing, and add it/them.

>> Can I find all of the unconserved (orphan) genes in fission yeast?
> 
> Since we don't have taxonomic distribution.
> It is possible to get an approximation using Queries though...

If you can supply a query, I could create a japonicus FAQ with it. Is that of interest?

>> How can I find GO annotations for other Schizosaccharomyces species?
> 
> We can delete this FAQ item from JaponicusDB AND PomBase, it was originally written for Snezhka!

This other FAQs links to it:

- Can I do GO term enrichment for other Schizosaccharomyces species?

@ValWood do you want to keep this one, and if so, how should we edit it?

Once that's sorted, @kimrutherford - is it safe to do `git rm` to trash the one about finding GO for other Schizos (or indeed both)?

>> Is there a list of protein complexes in S. japonicus, and their subunits?
> 
> Not applicable

what is this, chopped liver? https://www.japonicusdb.org/data/annotations/Gene_ontology/GO_complexes/Complex_annotation.tsv ;)

For anything not mentioned above, I've either edited the text or flagged the whole FAQ entry as PomBase-only.

**Comment by kimrutherford** [comment]
> Once that's sorted, @kimrutherford - is it safe to do git rm to trash the one about finding GO for other Schizos (or indeed both)?

Yep, no problem.

**Comment by ValWood** [comment]
Can I find all of the unconserved (orphan) genes in fission yeast?

>>If you can supply a query, I could create a japonicus FAQ with it. Is that of interest?

I just had a look, and without characterization status we can't do this at present.

**Comment by ValWood** [comment]
Can I do GO term enrichment for other Schizosaccharomyces species?
You can trash this FAQ too. If people ask we can figure out the best way (with caveats about the sub optimal GO data)

**Comment by ValWood** [comment]
>what is this, chopped liver?

Ooh there's a phase I haven't heard for years. I thought it was a norther thing!
Anyway, Cool that we have that!

**Comment by kimrutherford** [comment]
> I just had a look, and without characterization status we can't do this at present.

Are orphan genes those without orthologs?

We can do queries like this:
https://www.japonicusdb.org/results/from/id/784dc8fe-cb69-42ee-ba3c-5db329f543c3

That could be a link in the documentation or it could be a Commonly used query (in JaponicusDB).

**Comment by ValWood** [comment]
yes  but it also include genes in expanded families which are conserved, but the orthologs haven't been completely resolved.
This is one of the reasons I have 'characterization status' for fission yeast...

**Comment by mah11** [comment]
OK, 2 FAQs edited, and 2 deleted.

I'm gonna close this, and we can open a new ticket if & when we (read: Val) decides what to put in an "orphan gene" FAQ for japonicus. We've sorted the rest here.

relevant commits
https://github.com/pombase/website/commit/dae21ccf250fb11462d98ea166f5a70d5d2ccaa2
https://github.com/pombase/website/commit/6901fff25c3e2685b7edfecb58fc454816e1c73c
https://github.com/pombase/website/commit/9f90cf28cca2fc946fae21b010e8b006acbf6eed
https://github.com/pombase/website/commit/db855c58d114f1010a96583d44d790d987f86666
