### ISSUE TITLE
New FAQ: How can I find orthologs between S. japonicus and other Schizosaccharomyces species?

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#83]
How can I find orthologs between S. japonicus and other Schizosaccharomyces species?
For pombe use the Advanced query (commonly used query)
For other fission yeast orthologs use Ensembl Compara

**Comment by mah11** [comment]
I just re-read the question and answer for the FAQ named in the title, and it looks applicable to any of the Schizos (not even just pombe and japonicus). I'll add db-specific notes about the reciprocal common queries for S.p. and S.j.

I also now think I can edit the other-than-budding-yeast-and-human orthology FAQ to do for both, with some db-specific sections. That also means I won't have as much fiddly editing of faq-to-faq links.i

**Comment by mah11** [comment]
relevant commit
https://github.com/pombase/website/commit/9f90cf28cca2fc946fae21b010e8b006acbf6eed
