### ISSUE TITLE
New QuiLT comparison diagram for manuscript

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-config#84]
![quilt-comp-13-export](https://user-images.githubusercontent.com/90474/133047001-757ea6a5-6bb1-4640-83e4-65dcd0b0fc82.png)

**Comment by ValWood** [comment]
Looks good!

**Comment by kimrutherford** [comment]
Here is the PDF:

[japonicus-paper-quilt-diagram.pdf](https://github.com/japonicusdb/japonicus-config/files/7153905/japonicus-paper-quilt-diagram.pdf)

**Comment by mah11** [comment]
Incorporated into the manuscript, so closing :)
