### ISSUE TITLE
japonicus menus changed?

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#86]
I'm preparing my japonicus presentation for the GO meeting, and I think the menus have changed.

Under genome status, 'curation statistics' has disappeared, and some menus that aren't relevant to japonicus have appeared.

**Comment by mah11** [comment]
A couple of the menus -- About and Genome status -- are now managed in the website config JSON files, as first described [here](https://github.com/pombase/website/issues/1714#issuecomment-920506209). For those two I can remove whatever shouldn't be in the JaponicusDB menu. Which ones should get the ax? (For "PomBase curated publications" I'll just change the text, 'cos it actually already goes to the correct page.)

The menu-move comment also includes this from Kim:

> I've also temporarily removed the menu entry for "Curation statistics" as the page is a mess for japonicus. Let me know if you'd like that back.

If you think it's sufficiently less messy that it was 3 weeks ago, I'll add it back to the menu. Have a look; I'll wait until you give the go-ahead, and it'll be available next day once I commit changes.

https://curation.pombase.org/japonicus/stats/annotation

**Comment by ValWood** [comment]
we can remove
disease overview
Gene characterization statu
priority unstudied genes
Japonicus curated publications (they will all be community, so we only need one list)


although there is not data under
Gene coordinate changes
and
New and removed genes
we should keep those. 
We need a config format for these data.

We can leave the stats page until Kim gives the go ahead. I only wanted the total community annotation and I have that now.....
