### ISSUE TITLE
News item for JaponicusDB

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#88]
@kimrutherford 
draft announcement (use GO icon|) 
Title: JaponicusDB  disseminates data to the Gene Ontology database
The experimental annotations from S. japonicus community curated publications are now included in the GO database and visible in the AmiGO browser [example link http://amigo.geneontology.org/amigo/reference/PMID:29191091)]

@snezhkaoliferenko  DO you have a preference which publication to use as an example? it should be one with 'interesting' GO annotation, so I avoided any thick only had for instance localization data.

**Comment by kimrutherford** [comment]
The news item is ready to go when you're happy with the publication choice.

**Comment by ValWood** [comment]
I think we can publish. We can always switch.

**Comment by kimrutherford** [comment]
OK.  I've checked it in and it will be up on the site on Tuesday morning.
