### ISSUE TITLE
missing product

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#91]
Need to add product for SJAG_00535

**Comment by kimrutherford** [comment]
Hi Val.

The products for japonicus are here: https://github.com/japonicusdb/japonicus-curation/blob/main/names_and_products.tsv

(Manu, when we set up japonicusdb.org, we decided to put as little as possible in the "contig" files.  The names, products are synonyms are an example - they're in a TSV file in Git.)

**Comment by ValWood** [comment]
Done, I wasn't surre what it was. Nothing exciting.
SJAG_00535                      Schizosaccharomyces japonicus specific protein
