### ISSUE TITLE
"warnings" for japonicus

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#93]
I added 2 "warnings' to the contigs for  japonicus 
https://pomrt.gen.private.cam.ac.uk/rt/Ticket/ShowEmailRecord.html?id=9447&Transaction=126166&Attachment=115838

but I now realise these are not displayed. Is it easy to parse these from the contigs (I know we don't use. Japonicus contigs for anything else so this might be a pain...)

"Dear all,

I have updated the protein sequence is now

>SJAG_04697 - 324812: 326027 MW: 39598.69
MAMGEVTAWHGIPMKYISLVLLTFQNSALILILHYSCIMPGYEDKRYITSTAVLLNELIK
LSVCSAVAYNQFRKNAGADARKNAFLREIFSNDSWKLAIPAFLYTLQNNLQYVAAGNLPA
ATFQVTYQLKILTTALFSVLLLGRRLSLMKWCSLVVLTAGIAVVQLQNLQGGSSSEENSE
LNAKTGFVAVIVACLISGLAGVYFEKVLKGTKSSLWIRNIQLSFFSLVPCVFTIFWKNAA
DIVTHGFFFGYNYVVWTAIFFQAFGGIVVALCVAFADNIMKNFATSISILISFVASVYFF
DFAISASVCSSPRSQQLQLLTQECSFSSEVAWSFWLPFCTHGLKRKVSQRSLTFLSP

with an artifical frameshift, and 2 warnings:

/controlled_curation="term=warning, gene structure updated; date=
20220612"
/controlled_curation="term=warning frameshifted; date=20220612"

which is the best I can do for the time being.
I can add a reference to your paper when published.

**Comment by kimrutherford** [comment]
No problem.  It's just a configuration changes, which is done now.

The warning section should appear on the genes pages in the morning.

**Comment by ValWood** [comment]
Cool, your code is the best ;)

**Comment by kimrutherford** [comment]
> The warning section should appear on the genes pages in the morning

All done.
