### ISSUE TITLE
No community curation on japonicusdb.org

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-config#94]
https://www.japonicusdb.org/reference_list/community

I'm sure there used to be some?  @ValWood

**Comment by kimrutherford** [comment]
My guess is that it's related to the changes in pombase/website#525

I'll investigate soon.

**Comment by ValWood** [comment]
well spotted!

**Comment by kimrutherford** [comment]
> My guess is that it's related to the changes in pombase/website#525

I think it's happening because the Canto and website code changed, but I forgot to update the Canto code used by the japonicus Canto.  (The website code automatically updates)

The annotation is all there on the website.  It's just the curator information that's missing.

I've updated japonicus Canto and restarted it.  I'll check tomorrow to see if japonicusdb.org is fixed.

**Comment by kimrutherford** [comment]
All OK now.

**Comment by kimrutherford** [comment]
I'm not sure what going on with this session.  I expect it to say "Curation by Snezhana Oliferenko and Val Wood" (like in [this session](https://www.pombase.org/reference/PMID:26132084]):

![image](https://user-images.githubusercontent.com/90474/197327151-c351530b-3f94-47d0-b10f-b5adb59ac6e7.png)

It's not a huge bug but I want to check the code.

https://www.japonicusdb.org/reference/PMID:21802294

See: https://github.com/pombase/website/issues/525

**Comment by kimrutherford** [comment]
> I'm not sure what going on with this session. I expect it to say "Curation by Snezhana Oliferenko and Val Wood" 

It's OK.  The code works slightly differently for admin curators, but it's not wrong.

**Comment by ValWood** [comment]
Yes, I think 'everyone' is a community curator for japonicusDB maybe?

**Comment by kimrutherford** [comment]
> Yes, I think 'everyone' is a community curator for japonicusDB maybe?

We made a special case in JaponicusDB so that the names of admin curators are displayed on the publication pages.  In PomBase we just say "Curated by PomBase staff".
