### ISSUE TITLE
Japonicus news items

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#96]
Include experiments; structures from pdf news item and advanced search common query if there are any japonicas structures

Include Alpha field news item on the japonicus news feed

**Comment by kimrutherford** [comment]
I've added an article about AlphaFold (for Thursday morning).  I forgot to change the load script to add japonicus PDB IDs to Chado so we can't query for genes with PDB IDs yet.  I'll fix that and then add a news item.

**Comment by ValWood** [comment]
I don't  know if there are any structures but I think  I remember at least 1

**Comment by kimrutherford** [comment]
> https://www.japonicusdb.org/results/from/id/0c97da98-0210-404b-840e-f98bfb2b5aeb

There's 5 but because the PDB IDs aren't in japonicus Chado, the structures aren't shown.

**Comment by kimrutherford** [comment]
> There's 5 but because the PDB IDs aren't in japonicus Chado, the structures aren't shown.

They should be visible tomorrow on the pages for: PMID:26343758, PMID:35693892, SJAG_03867, SJAG_04265 and SJAG_03542.

I'll check in the morning.

**Comment by kimrutherford** [comment]
> They should be visible tomorrow on the pages for: PMID:26343758, PMID:35693892, SJAG_03867, SJAG_04265 and SJAG_03542.
>
> I'll check in the morning.

That seemed to work:
 - https://www.japonicusdb.org/reference/PMID:26343758
 - https://www.japonicusdb.org/gene/SJAG_03867

I'll add a news item.

**Comment by kimrutherford** [comment]
One publication page that for a publication with a structure is missing due to a configuration problem:
https://www.japonicusdb.org/reference/PMID:35693892

I've fixed that for tomorrow's update.

**Comment by kimrutherford** [comment]
I've added a news item about the PDB structures for japonicus.  It will be visible in the morning.

**Comment by ValWood** [comment]
@snezhkaoliferenko 
there is also a "commonly used query" i the advanced search that will provide all proteins with pdb structures in case you ever want to find them all.
Only 3 right now:
https://www.japonicusdb.org/results/from/id/13956cc1-e668-409f-a0ea-ae9c30bf3a60

**Comment by snezhkaoliferenko** [comment]
thanks!
