### ISSUE TITLE
Maybe link to "JapoNet" - Niki lab?

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-config#98]
It could be an FAQ: Where do I find more information about S. japonicus?

https://shigen.nig.ac.jp/yeast/japonet/index.html

**Comment by ValWood** [comment]
Good idea

**Comment by kimrutherford** [comment]
That's done but it's very minimal:
https://www.japonicusdb.org/faq/where-do-i-find-more-information-about-s.-japonicus

It's here if you want to add to it:
https://github.com/pombase/website/edit/master/src/docs/faq/how-do-i-find-more-about-s-japonicus.JaponicusDB.md
