### ISSUE TITLE
Add the protein feature viewer widget

### ISSUE THREAD

**Issue by kimrutherford** [japonicusdb/japonicus-config#99]

**Comment by kimrutherford** [comment]
I've added the configuration.  The feature should appear for PomBase and JaponicusDB at the same time.

**Comment by kimrutherford** [comment]
@snezhkaoliferenko This is the prototype on the PomBase dev site: http://dev.pombase.kmr.nz/gene_protein_features/SPAC140.02

**Comment by snezhkaoliferenko** [comment]
Looks great! On the left, when one hovers over the categories, are there little drop down arrows? do you want them to lead to details eventually?
PS: Love the color scheme ;)

**Comment by kimrutherford** [comment]
> On the left, when one hovers over the categories, are there little drop down arrows? do you want them to lead to details eventually?

I'm experimenting with a "tooltip" that describes each row when you hover over the category titles.  Is that what you were thinking of?

This screenshot is from my desktop in NZ (available until about 1pm UK time each day): https://desktop.kmr.nz/gene_protein_features/SPBC1778.02


![image](https://github.com/japonicusdb/japonicus-config/assets/90474/802341b6-1415-46ab-a59e-91d22d3d895a)

**Comment by snezhkaoliferenko** [comment]
Oh I see, melikes!

**Comment by kimrutherford** [comment]
We've release the new protein feature viewer for PomBase: https://www.pombase.org/gene_protein_features/SPAC20G8.05c

It will be released on japonicusdb.org later today.

**Comment by snezhkaoliferenko** [comment]
thank you!!!
________________________________

**Comment by kimrutherford** [comment]
Done!  https://www.japonicusdb.org/gene/SJAG_03596

**Comment by snezhkaoliferenko** [comment]
my heart! thank you!
________________________________
